CREATE OR REPLACE FUNCTION SEM_BOOL_TO_STRING(p_bool NUMBER)
RETURN VARCHAR2 DETERMINISTIC IS
begin
    IF p_bool > 0 THEN
        RETURN 'Ano';
    ELSE
        RETURN 'Ne';
    END IF;
end;

/

CREATE OR REPLACE FUNCTION SEM_DATUM_NA_DEN(p_datum DATE)
RETURN NUMBER DETERMINISTIC IS
BEGIN
    RETURN TRUNC(p_datum) - TRUNC (p_datum, 'IW');
END;