
-- region Fakulty: ------------------------------------------------------------------------------------------------------------
INSERT INTO SEM_FAKULTA (ID, ZKRATKA, NAZEV)
VALUES (SEM_FAKULTA_SEQ.NEXTVAL, 'DFJ', 'Dopravní fakulta Jana Pernera');

INSERT INTO SEM_FAKULTA (ID, ZKRATKA, NAZEV)
VALUES (SEM_FAKULTA_SEQ.NEXTVAL, 'FEI', 'Fakulta elektrotechniky a informatiky');

INSERT INTO SEM_FAKULTA (ID, ZKRATKA, NAZEV)
VALUES (SEM_FAKULTA_SEQ.NEXTVAL, 'FES', 'Fakulta ekonomicko-správní');

INSERT INTO SEM_FAKULTA (ID, ZKRATKA, NAZEV)
VALUES (SEM_FAKULTA_SEQ.NEXTVAL, 'FF', 'Fakulta filozofická');

INSERT INTO SEM_FAKULTA (ID, ZKRATKA, NAZEV)
VALUES (SEM_FAKULTA_SEQ.NEXTVAL, 'FCH', 'Fakulta chemicko-technologická');

INSERT INTO SEM_FAKULTA (ID, ZKRATKA, NAZEV)
VALUES (SEM_FAKULTA_SEQ.NEXTVAL, 'FR', 'Fakulta restaurování');

INSERT INTO SEM_FAKULTA (ID, ZKRATKA, NAZEV)
VALUES (SEM_FAKULTA_SEQ.NEXTVAL, 'FZS', 'Fakulta zdravotnických studií');

INSERT INTO SEM_FAKULTA (ID, ZKRATKA, NAZEV)
VALUES (SEM_FAKULTA_SEQ.NEXTVAL, 'REK', 'Univerzita Pardubice');

-- endregion

-- region Katedry: ------------------------------------------------------------------------------------------------------------

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'ARK', 6.0, 'Atelier restaurovani kamene');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'ARMS', 6.0, 'Atelier restaurovani malby a sgrafita');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'ARPKVD', 6.0, 'Atelier restaurovani papiru, knizni vazby a dokumentu');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'ARUDP', 6.0, 'Atelier restaurovani umeleckych del na papiru');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'AVP', 6.0, 'Atelier vytvarne pripravy');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'CEMNAT', 1.0, 'Centrum materialu a nanotechnologii');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'JC', 8.0, 'Jazykove centrum');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KAA', 4.0, 'Katedra anglistiky a amerikanistiky');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KALCH', 1.0, 'Katedra analyticke chemie');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KANT', 1.0, 'Katedra anorganicke technologie');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KBBV', 1.0, 'Katedra biologickych a biochemickych ved');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KCJ', 4.0, 'Katedra cizich jazyku');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KCJFR', 6.0, 'Katedra cizich jazyku FR');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KDCP', 1.0, 'Katedra dreva, celulozy a papiru');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KDMML', 1.0, 'Katedra dopravniho managementu, marketingu a logistiky');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KDPD', 1.0, 'Katedra dopravnich prostredku a diagnostiky');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KDS', 1.0, 'Katedra dopravniho stavitelstvi');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KE', 2.0, 'Katedra elektrotechniky');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KEEZ', 1.0, 'Katedra elektrotechniky, elektroniky a zabezpecovaci techniky v doprave');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KEMCH', 1.0, 'Katedra ekonomiky a managementu chemickeho a potravinarskeho prumyslu');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KFCH', 1.0, 'Katedra fyzikalni chemie');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KFI', 4.0, 'Katedra filosofie');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KHV', 4.0, 'Katedra historickych ved');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KHVFR', 6.0, 'Katedra humanitnich ved FR');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KCHI', 1.0, 'Katedra chemickeho inzenyrstvi');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KCHTFR', 6.0, 'Katedra chemicke technologie FR');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KID', 1.0, 'Katedra informatiky v doprave');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KIR', 7.0, 'Katedra informatiky, managementu a radiologie');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KIT', 2.0, 'Katedra informacnich technologii');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KJPSD', 1.0, 'Katedra jakosti, provozni spolehlivosti a diagnostiky v doprave');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KKO', 7.0, 'Katedra klinickych oboru');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KLKS', 4.0, 'Katedra literarni kultury a slavistiky');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KMF', 2.0, 'Katedra matematiky a fyziky');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KMMCS', 1.0, 'Katedra mechaniky, materialu a casti stroju');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KOANCH', 1.0, 'Katedra obecne a anorganicke chemie');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KOCH', 1.0, 'Katedra organicke chemie');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KOS', 7.0, 'Katedra osetrovatelstvi');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KPF', 1.0, 'Katedra polygrafie a fotofyziky');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KPZ', 7.0, 'Katedra porodni asistence a zdravotne socialni prace');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KRE', 4.0, 'Katedra religionistiky');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KRF', 4.0, 'Katedra religionistiky a filosofie');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KRP', 2.0, 'Katedra rizeni procesu');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KRPVT', 1.0, 'Katedra rizeni procesu a vypocetni techniky');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KST', 2.0, 'Katedra softwarovych technologii');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KSV', 4.0, 'Katedra socialnich ved');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KTOL', 1.0, 'Katedra technologie organickych latek');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KTRD', 1.0, 'Katedra technologie a rizeni dopravy');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KTS', 8.0, 'Katedra telovychovy a sportu');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KTTV', 1.0, 'Katedra teorie a technologie vybusin');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'KVV', 4.0, 'Katedra ved o vychove');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'SLCHPL', 1.0, 'Spolecna laborator chemie pevnych latek');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'UAFM', 1.0, 'Ustav aplikovane fyziky a matematiky');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'UCJ', 4.0, 'Ustav cizich jazyku');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'UECHI', 1.0, 'Ustav environmentalniho a chemickeho inzenyrstvi');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'UENM', 1.0, 'Ustav energetickych materialu');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'UEV', 3.0, 'Ustav ekonomickych ved');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'UHV', 4.0, 'Ustav historickych ved');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'UCHTML', 1.0, 'Ustav chemie a technologie makromolekularnich latek');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'UI', 8.0, 'Ustav elektrotechniky a informatiky');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'UK', 8.0, 'Univerzitni knihovna');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'UMKM', 3.0, 'Ustav matematiky a kvantitativnich metod');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'UOCHT', 1.0, 'Ustav organicke chemie a technologie');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'UOZP', 1.0, 'Ustav ochrany zivotniho prostredi');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'UPEM', 3.0, 'Ustav podnikove ekonomiky a managementu');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'UPM', 1.0, 'Ustav polymernich materialu');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'URBV', 3.0, 'Ustav regionalnich a bezpecnostnich ved');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'USII', 3.0, 'Ustav systemoveho inzenyrstvi a informatiky');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'USSV', 3.0, 'Ustav spravnich a socialnich ved');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'UZS', 8.0, 'Fakulta zdravotnickych studii');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'VIP', 1.0, 'Vzdelavaci a informacni pracoviste DFJP');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'VVCD', 1.0, 'Vyukove a vyzkumne centrum v doprave');

INSERT INTO SEM_KATEDRA (ID, ZKRATKA, FAKULTA_ID, NAZEV)
VALUES (SEM_KATEDRA_SEQ.NEXTVAL, 'VZC', 1.0, 'Vyzkumne centrum LN0A028');

-- endregion

-- region Ucitele ------------------------------------------------------------------------------------------------------------

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'lubomir.andrle@upce.cz', '', '', 29.0, 'Lubomir', 'Andrle');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, '', '', '', '', '', 29.0, 'Eduard', 'Babulak');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'michael.bazant@upce.cz', '466 037 224', '', 44.0, 'Michael', 'Bazant');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'RNDr.', '', 'bene@fria.fri.utc.sk', '', '', 44.0, 'Miroslav', 'Benedikovic');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'st25775@student.upce.cz', '', '', 18.0, 'Ladislav', 'Beran');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'prof. Ing.', 'CSc.', 'pavel.bezousek@upce.cz', '', '', 18.0, 'Pavel', 'Bezousek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'vojtech.biberle@upce.cz', '', '', 29.0, 'Vojtech', 'Biberle');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 18.0, 'Jiri', 'Blecha');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'agata.bodnarova@gmail.com', '', '', 18.0, 'Agata', 'Bodnarova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, '', '', '', '', '', 18.0, 'Jiri', 'Boch');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'monika.borkovcova@upce.cz', '', '', 29.0, 'Monika', 'Borkovcova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Bc.', '', '', '', '', 44.0, 'Filip', 'Borovec');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', '', 'tereza.bosakova@upce.cz', '', '', 6.0, 'Tereza', 'Bosakova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'doc. Ing.', 'Dr.', 'Tomas.Brandejsky@upce.cz', '', '', 44.0, 'Tomas', 'Brandejsky');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 18.0, 'Vladimir', 'Brazda');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'pavel.brom@upce.cz', '', '', 44.0, 'Pavel', 'Brom');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'josef.brozek@student.upce.cz', '', '', 29.0, 'Josef', 'Brozek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Dr.', '', '', '', 18.0, 'Bohumil', 'Brtnik');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, '', '', 'david.budac@upce.cz', '', '', 29.0, 'David', 'Budac');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 29.0, 'Lukas', 'Cir');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'doc. Ing.', 'Ph.D.', 'jan.cvejn@upce.cz', '', '', 42.0, 'Jan', 'Cvejn');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'jiri.cadek@student.upce.cz', '', '', 6.0, 'Jiri', 'Cadek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'lukas.cegan@upce.cz', '', '', 29.0, 'Lukas', 'Cegan');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'matej.cerny@student.upce.cz', '', '', 18.0, 'Matej', 'Cerny');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'roman.divis@student.upce.cz', '', '', 44.0, 'Roman', 'Divis');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'monika.dobesova@upce.cz', '', '', 29.0, 'Monika', 'Dobesova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'martin.dobrovolny@upce.cz', '', '', 18.0, 'Martin', 'Dobrovolny');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'doc. Ing.', 'Ph.D.', 'Petr.Dolezel@upce.cz', '', '', 42.0, 'Petr', 'Dolezel');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'doc. Ing.', 'CSc.', 'frantisek.dusek@upce.cz', '', '', 42.0, 'Frantisek', 'Dusek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'michal.dvorak@student.upce.cz', '', '', 6.0, 'Michal', 'Dvorak');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Dipl.tech.', 'miroslav.dvorak@upce.cz', '', '', 29.0, 'Miroslav', 'Dvorak');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 44.0, 'Tomas', 'Dvorak');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', 'Ph.D.', '', '', '', 33.0, 'Kamila', 'Facevicova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 29.0, 'Ilona', 'Fialova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'tomas.fidler@tiscali.cz', '466 036 475', '', 44.0, 'Tomas', 'Fidler');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'jan.fikejz@upce.cz', '', '', 44.0, 'Jan', 'Fikejz');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'doc. Ing.', 'CSc.', 'ales.filip@upce.cz', '', '', 18.0, 'Ales', 'Filip');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'petr.filip1@student.upce.cz', '', '', 29.0, 'Petr', 'Filip');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'doc. Ing.', 'CSc.', 'ondrej.fiser@upce.cz', '', '', 18.0, 'Ondrej', 'Fiser');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Dr.', 'miroslav.fribert@upce.cz', '', '', 18.0, 'Miroslav', 'Fribert');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'lumir.gago@student.upce.cz', '', '', 29.0, 'Lumir', 'Gago');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'martin.hajek@student.upce.cz', '', '', 18.0, 'Martin', 'Hajek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'david.handlir@student.upce.cz', '', '', 29.0, 'David', 'Handlir');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'Milan.Hanus@upce.cz', '', '', 18.0, 'Milan', 'Hanus');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'libor.havlicek@upce.cz', '', '', 42.0, 'Libor', 'Havlicek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 44.0, 'Martin', 'Hazer');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing. Mgr.', 'Ph.D.', 'hlinka@cs.cas.cz', '', '', 42.0, 'Jaroslav', 'Hlinka');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'tomas.hnilicka@student.upce.cz', '', '', 18.0, 'Tomas', 'Hnilicka');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'filip.holik@student.upce.cz', '', '', 29.0, 'Filip', 'Holik');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'daniel.honc@upce.cz', '', '', 42.0, 'Daniel', 'Honc');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, '', '', 'paul.hooper@upce.cz', '46 603 6710', '', 6.0, 'Paul Charles', 'Hooper');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'michal.horacek.czech@gmail.com', '', '', 18.0, 'Michal', 'Horacek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'JUDr.', '', 'pavel.horak@upce.cz', '', '', 29.0, 'Pavel', 'Horak');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', 'Ph.D.', 'josef.horalek@upce.cz', '466 036 488', '', 29.0, 'Josef', 'Horalek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', 'Ph.D.', 'Klara.Hruzova@upce.cz', '', '', 33.0, 'Klara', 'Hruzova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'jan.hridel@upce.cz', '', '', 44.0, 'Jan', 'Hridel');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', '', 'tomas.hudec@upce.cz', '', '', 29.0, 'Tomas', 'Hudec');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'veronika.hurtova@student.upce.cz', '', '', 29.0, 'Veronika', 'Hurtova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'st19544@student.upce.cz', '', '', 18.0, 'Pavel', 'Chmelar');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, '', '', 'dana.jablonska@upce.cz', '', '', 29.0, 'Dana', 'Jablonska');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 18.0, 'Michal', 'Jachim');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'martin.jakes@student.upce.cz', '', '', 44.0, 'Martin', 'Jakes');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 18.0, 'Otakar', 'Jaros');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'doc. Ing.', 'CSc.', 'milan.javurek@upce.cz', '', '', 42.0, 'Milan', 'Javurek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing. Mgr.', 'Ph.D.', 'radim.jelinek@mmp.cz', '', '', 29.0, 'Radim', 'Jelinek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Bc.', '', '', '', '', 29.0, 'Simon', 'Jelinek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', 'DiS.', 'hana.jelinkova@upce.cz', '', '', 29.0, 'Hana', 'Jelinkova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 18.0, 'Jakub', 'Jerabek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'st33370@student.upce.cz', '', '', 29.0, 'Pavel', 'Jetensky');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'milan.jicinsky@student.upce.cz', '', '', 42.0, 'Milan', 'Jicinsky');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, '', '', 'petra.jiristova@upce.cz', '466 036 423', '', 6.0, 'Petra', 'Jiristova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'marek.jonas@student.upce.cz', '', '', 18.0, 'Marek', 'Jonas');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'karel.juryca@student.upce.cz', '', '', 33.0, 'Karel', 'Juryca');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'prof. Ing.', 'Dr.', 'simeon.karamazov@upce.cz', '', '', 29.0, 'Simeon', 'Karamazov');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'st12656@student.upce.cz', '', '', 18.0, 'Ondrej', 'Karas');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'stepan.kartak@student.upce.cz', '', '', 44.0, 'Stepan', 'Kartak');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'prof. Ing.', 'Ph.D.', 'antonin.kavicka@upce.cz', '466 036 645', '', 44.0, 'Antonin', 'Kavicka');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'jan.keller@student.upce.cz', '', '', 29.0, 'Jan', 'Keller');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'zuzana.kleprlikova@upce.cz', '', '', 29.0, 'Zuzana', 'Kleprlikova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'jiri.konecny@upce.cz', '', '', 18.0, 'Jiri', 'Konecny');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Bc.', '', '', '', '', 29.0, 'Lubos', 'Kopecky');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'zbynek.kopecky@upce.cz', '', '', 29.0, 'Zbynek', 'Kopecky');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', '', '', '', '', 6.0, 'David', 'Kordek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'pavla.kotatkovastranska@upce.cz', '', '', 33.0, 'Pavla', 'Kotatkova Stranska');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'doc. Ing.', 'CSc.', 'josef.kotyk@upce.cz', '', '', 42.0, 'Josef', 'Kotyk');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'jaroslava.kralova@student.upce.cz', '', '', 42.0, 'Jaroslava', 'Kralova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'jiri.kratochvil@student.upce.cz', '', '', 29.0, 'Jiri', 'Kratochvil');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Bc.', '', '', '', '', 29.0, 'David', 'Krejca');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'doc. Ing.', 'CSc.', 'stanislav.krejci@upce.cz', '', '', 42.0, 'Stanislav', 'Krejci');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'tomas.krejci2@student.upce.cz', '', '', 18.0, 'Tomas', 'Krejci');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'jaroslav.kricka@upce.cz', '', '', 18.0, 'Jaroslav', 'Kricka');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 44.0, 'Pavel', 'Kriz');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Bc.', '', '', '', '', 6.0, 'Ilona', 'Kucerova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'st44226@student.upce.cz', '', '', 18.0, 'Nataliia', 'Kudriavtseva');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'kudyn@szdc.cz', '', '', 18.0, 'Vladimir', 'Kudyn');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'Libor.Kupka@upce.cz', '', '', 42.0, 'Libor', 'Kupka');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'CSc.', '', '', '', 18.0, 'Vaclav', 'Kvicera');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'jiri.kysela@upce.cz', '', '', 29.0, 'Jiri', 'Kysela');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'jaroslav.lach@upce.cz', '', '', 44.0, 'Jaroslav', 'Lach');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'st19560@student.upce.cz', '', '', 18.0, 'Martin', 'Lauterbach');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'jiri.lebduska@student.upce.cz', '', '', 29.0, 'Jiri', 'Lebduska');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', '', '', '', 18.0, 'Michal', 'Lekyr');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'doc. Ing.', 'CSc.', 'jiri.machacek@upce.cz', '', '', 42.0, 'Jiri', 'Machacek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'miloslav.machacek@upce.cz', '', '', 29.0, 'Miloslav', 'Machacek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'st40429@student.upce.cz', '', '', 44.0, 'Filip', 'Majerik');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, '', '', 'Jitka.Malkova@upce.cz', '', '', 42.0, 'Jitka', 'Malkova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'michal.mandlik@student.upce.cz', '', '', 18.0, 'Michal', 'Mandlik');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', 'Ph.D.', 'jaroslav.marek@upce.cz', '', '', 33.0, 'Jaroslav', 'Marek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'CSc.', 'josef.marek@upce.cz', '', '', 18.0, 'Josef', 'Marek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'Jan.Mares@vscht.cz', '', '', 44.0, 'Jan', 'Mares');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'mariska.martin@gmail.com', '', '', 42.0, 'Martin', 'Mariska');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'st22222@student.upce.cz', '', '', 44.0, 'Ondrej', 'Marik');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing. Bc.', '', 'david.matousek@upce.cz', '', '', 18.0, 'David', 'Matousek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 6.0, 'Jakub', 'Mejznar');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', '', 'Lucie.Vycitalova@upce.cz', '', '', 29.0, 'Lucie', 'Melicharova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'jan.merta@student.upce.cz', '', '', 44.0, 'Jan', 'Merta');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, '', '', 'jana.mikulecka@upce.cz', '', '', 42.0, 'Jana', 'Mikulecka');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'PhDr.', '', 'olga.mitchell@upce.cz', '+420773758223', '', 6.0, 'Olga', 'Mitchell');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'RNDr. et PhDr.', 'Ph.D.', 'ivo.muller@upce.cz', '', '', 33.0, 'Ivo', 'M�ller');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'martin.navratil1@student.upce.cz', '', '', 18.0, 'Martin', 'Navratil');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'marie.nedvedova@student.upce.cz', '', '', 33.0, 'Marie', 'Nedvedova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'zdenek.nemec@upce.cz', '', '', 18.0, 'Zdenek', 'Nemec');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'sona.neradova@upce.cz', '466 603 7004', '', 29.0, 'Sona', 'Neradova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'miroslav.novosvetsky@student.upce.cz', '', '', 29.0, 'Miroslav', 'Novosvetsky');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', '', 'darina.novotna@upce.cz', '', '', 29.0, 'Darina', 'Novotna');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', '', 'milan.novotny@upce.cz', '', '', 29.0, 'Milan', 'Novotny');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 44.0, 'Radek', 'Novotny');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', '', '', '', 18.0, 'Frantisek', 'Ondracek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'doc. Mgr.', 'Ph.D.', 'karel.pastor@upce.cz', '', '', 33.0, 'Karel', 'Pastor');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'RNDr.', 'Ph.D.', '', '', '', 33.0, 'Martina', 'Pavlackova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 18.0, 'Viktor', 'Pek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'st29660@student.upce.cz', '', '', 18.0, 'Jiri', 'Pesek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 6.0, 'Petra', 'Peskova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'st18322@student.upce.cz', '', '', 18.0, 'Matej', 'Petkov');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Bc.', '', '', '', '', 29.0, 'Ondrej', 'Petrzilka');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'jan.pidanic@upce.cz', '', '', 18.0, 'Jan', 'Pidanic');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'milena.cepcarova@upce.cz', '', '', 6.0, 'Milena', 'Podebradska');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'marek.pola@upce.cz', '', '', 18.0, 'Marek', 'Pola');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', 'Ph.D.', 'alena.pozdilkova@upce.cz', '', '', 33.0, 'Alena', 'Pozdilkova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'jan.pruska@projectsoft.cz', '', '', 42.0, 'Jan', 'Pruska');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'dana.privratska@upce.cz', '', '', 29.0, 'Dana', 'Privratska');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'zdenek.privratsky@upce.cz', '', '', 29.0, 'Zdenek', 'Privratsky');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'RNDr.', 'Ph.D.', 'josef.rak@upce.cz', '', '', 33.0, 'Josef', 'Rak');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'st16660@student.upce.cz', '', '', 18.0, 'Lubos', 'Rejfek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'jiri.rolecek@upce.cz', '', '', 18.0, 'Jiri', 'Rolecek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'pavel.rozsival@upce.cz', '', '', 18.0, 'Pavel', 'Rozsival');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'RNDr.', '', 'iva.rulicova@upce.cz', '466 037 096', '', 33.0, 'Iva', 'Ruli�ova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'emil.rezanina@upce.cz', '', '', 29.0, 'Emil', 'Rezanina');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'vojtech.samotan@student.upce.cz', '', '', 44.0, 'Vojtech', 'Samotan');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Bc.', '', '', '', '', 29.0, 'Michal', 'Seifert');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'st22083@student.upce.cz', '', '', 18.0, 'Tomas', 'Shejbal');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Bc.', '', 'klara.schejbalova@upce.cz', '', '', 18.0, 'Klara', 'Schejbalova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 42.0, 'S.', 'Scholle');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 44.0, 'Vladimir', 'Sieber');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'stanislava.slanska@upce.cz', '', '', 29.0, 'Stanislava', 'Slanska');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'lukas.slansky@upce.cz', '', '', 29.0, 'Lukas', 'Slansky');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', '', '', '', '', 29.0, 'Miroslav', 'Suchy');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'RNDr.', '', 'martin.svoboda@upce.cz', '', '', 33.0, 'Martin', 'Svoboda');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'tomas.svoboda5@student.upce.cz', '', '', 29.0, 'Tomas', 'Svoboda');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Bc.', '', '', '', '', 18.0, 'Miroslav', 'Sedivy');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', '', 'pavel.sevcik@purpure.cz', '', '', 18.0, 'Pavel', 'Sevcik');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'zdenek.silar@upce.cz', '', '', 29.0, 'Zdenek', 'Silar');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'karel.simerda@upce.cz', '', '', 44.0, 'Karel', 'Simerda');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', 'pavel.skrabanek@upce.cz', '', '', 42.0, 'Pavel', 'Skrabanek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'prof. Ing.', 'CSc.', 'karel.sotek@upce.cz', '466 036 508', '', 44.0, 'Karel', 'Sotek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'jan.stafa@student.upce.cz', '', '', 29.0, 'Jan', 'Stafa');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'stanislav.stastny@upce.cz', '', '', 29.0, 'Stanislav', 'Stastny');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 18.0, 'Ladislav', 'Stepanek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'j.stroch@seznam.cz', '', '', 29.0, 'Jaroslav', 'Stroch');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'petr.suba@upce.cz', '', '', 44.0, 'Petr', 'Suba');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', '', '', '', 29.0, 'Pavel', 'Subrt');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', '', 'tomas.talasek@upce.cz', '', '', 33.0, 'Tomas', 'Talasek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'prof. Ing.', 'DrSc.', 'ivan.taufer@upce.cz', '', '', 42.0, 'Ivan', 'Taufer');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Bc.', '', 'lenka.tobiskova@upce.cz', '', '', 6.0, 'Lenka', 'Tobiskova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'jiri.tvrdik@student.upce.cz', '', '', 42.0, 'Jiri', 'Tvrdik');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', 'Ph.D.', 'zbynek.urban@upce.cz', '', '', 33.0, 'Zbynek', 'Urban');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'st19054@student.upce.cz', '', '', 29.0, 'Tomas', 'Vana');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'petr.vesely@upce.cz', '466 036 531', '', 44.0, 'Petr', 'Vesely');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', '', '', '', '', 29.0, 'Sona', 'Vinopalova');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', 'Ph.D.', '', '', '', 18.0, 'Radim', 'Vondra');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'jan.voracek@student.upce.cz', '', '', 29.0, 'Jan', 'Voracek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', '', 'jaroslav.vozab@upce.cz', '', '', 33.0, 'Jaroslav', 'Vozab');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Mgr.', '', 'janet.wolf@upce.cz', '+420604769254', '', 6.0, 'Janet', 'Wolf');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'tomas.zalabsky@student.upce.cz', '', '', 18.0, 'Tomas', 'Zalabsky');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'ludek.zaplatilek@student.upce.cz', '', '', 18.0, 'Ludek', 'Zaplatilek');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'milan.zapletal1@student.upce.cz', '', '', 42.0, 'Milan', 'Zapletal');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'zavodnv@post.cz', '', '', 18.0, 'Vadim', 'Zavodny');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'Jiri.Zechmeister@upce.cz', '', '', 29.0, 'Jiri', 'Zechmeister');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Bc.', '', 'st12581@student.upce.cz', '', '', 29.0, 'Jan', 'Zikl');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'Ing.', '', 'stanislav.zitta@student.upce.cz', '', '', 44.0, 'Stanislav', 'Zitta');

INSERT INTO SEM_UCITEL (ID, TITUL_PRED, TITUL_ZA, KONTAKTNI_EMAIL, TELEFON, MOBIL, KATEDRA_ID, JMENO, PRIJMENI)
VALUES (SEM_UCITEL_SEQ.NEXTVAL, 'RNDr.', 'Ph.D.', 'david.zak@upce.cz', '', '', 29.0, 'David', 'Zak');

-- endregion

-- region Kategorie: ---------------------------------------------------------------------------------------------------------

INSERT INTO SEM_KATEGORIE(ID, NAZEV)
VALUES (SEM_KATEGORIE_SEQ.NEXTVAL, 'A');

INSERT INTO SEM_KATEGORIE(ID, NAZEV)
VALUES (SEM_KATEGORIE_SEQ.NEXTVAL, 'B');

INSERT INTO SEM_KATEGORIE(ID, NAZEV)
VALUES (SEM_KATEGORIE_SEQ.NEXTVAL, 'C');

-- endregion

-- region Semestry: ---------------------------------------------------------------------------------------------------

INSERT INTO SEM_SEMESTR(ID, NAZEV)
VALUES (SEM_SEMESTR_SEQ.NEXTVAL, 'LS');

INSERT INTO SEM_SEMESTR(ID, NAZEV)
VALUES (SEM_SEMESTR_SEQ.NEXTVAL, 'ZS');

-- endregion

-- region Forma výuky: -------------------------------------------------------------------------------------------------------

INSERT INTO SEM_FORMA_VYUKY (ID, NAZEV)
VALUES (SEM_FORMA_VYUKY_SEQ.NEXTVAL, 'Prezencni');

INSERT INTO SEM_FORMA_VYUKY (ID, NAZEV)
VALUES (SEM_FORMA_VYUKY_SEQ.NEXTVAL, 'Kombinovana');

INSERT INTO SEM_FORMA_VYUKY (ID, NAZEV)
VALUES (SEM_FORMA_VYUKY_SEQ.NEXTVAL, 'Distancni');

-- endregion

-- region Role: --------------------------------------------------------------------------------------------------------------

INSERT INTO SEM_ROLE (ID, NAZEV)
VALUES (SEM_ROLE_SEQ.NEXTVAL, 'Přednasejici');

INSERT INTO SEM_ROLE (ID, NAZEV)
VALUES (SEM_ROLE_SEQ.NEXTVAL, 'Cvicici');

-- endregion

-- region Způsob výuky: -----------------------------------------------------------------------------------------------------

INSERT INTO SEM_ZPUS_VYUKY (ID, NAZEV)
VALUES (SEM_ZPUSOB_VYUKY_SEQ.NEXTVAL, 'Přednaska');

INSERT INTO SEM_ZPUS_VYUKY (ID, NAZEV)
VALUES (SEM_ZPUSOB_VYUKY_SEQ.NEXTVAL, 'Seminar');

INSERT INTO SEM_ZPUS_VYUKY (ID, NAZEV)
VALUES (SEM_ZPUSOB_VYUKY_SEQ.NEXTVAL, 'Cviceni');

-- endregion

-- region Zpusob zakonceni: -------------------------------------------------------------------------------------------------

INSERT INTO SEM_ZPUS_ZAK (ID, NAZEV)
VALUES (SEM_ZPUSOB_ZAKONCENI_SEQ.NEXTVAL, 'Zkouska');

INSERT INTO SEM_ZPUS_ZAK (ID, NAZEV)
VALUES (SEM_ZPUSOB_ZAKONCENI_SEQ.NEXTVAL,'Zapocet');

INSERT INTO SEM_ZPUS_ZAK (ID, NAZEV)
VALUES (SEM_ZPUSOB_ZAKONCENI_SEQ.NEXTVAL,'Klasifikovany zapocet');

-- endregion

-- region Obory: --------------------------------------------------------------------------------------------------

INSERT INTO SEM_OBOR (ID, NAZEV) VALUES (SEM_OBOR_SEQ.NEXTVAL, 'Informacni technologie');

INSERT INTO SEM_OBOR (ID, NAZEV) VALUES (SEM_OBOR_SEQ.NEXTVAL, 'Řízeni procesu');

INSERT INTO SEM_OBOR (ID, NAZEV) VALUES (SEM_OBOR_SEQ.NEXTVAL, 'Komunikacni a mikroprocesorova technika');

-- endregion

-- region Studijní plany: ----------------------------------------------------------------------------------------------------

-- FEI

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Elektrotechnika a informatika - Bakalar', 100, 2);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Elektrotechnika a informatika - Inzenyr', 60, 2);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Elektrotechnika a informatika - Doktor', 40, 2);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Informacni technologie - Bakalar', 40, 1);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Informacni technologie - Inzenyr', 40, 1);

-- DOPRAVNI

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Dopravní inženýrství a spoje - Inzenyr', 60, 2);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Dopravní technologie a spoje - Bakalar', 60, 2);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Stavební inženýrství - Bakalar', 40, 2);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Stavební inženýrství - Inzenyr', 50, 2);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Technika a technologie v dopravě - Doktor', 50, 2);

--- CHEMIE

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Analytická chemie - Doktor', 50, 3);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Anorganická chemie - Doktor', 50, 3);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Anorganické a polymerní materiály - Bakalář', 50, 3);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Farmakochemie a medicinální materiály - Bakalář', 50, 3);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Fyzikální chemie - Doktor', 70, 3);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Chemické a procesní inženýrství - Bakalář', 70, 3);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Chemické a procesní inženýrství - Doktor', 70, 3);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Chemické a procesní inženýrství - Inženýr', 70, 3);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Chemie - Inženýr', 70, 3);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Chemie a chemické technologie - Doktor', 30, 3);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Chemie a technická chemie - Bakalář', 30, 3);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Chemie a technologie materiálů - Doktor', 40, 1);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Chemie a technologie materiálů - Inženýr', 40, 1);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Chemie a technologie potravin - Bakalář', 40, 1);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Chemie a technologie potravin - Inženýr', 40, 1);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Organická chemie - Doktor', 40, 1);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Polygrafie - Bakalář', 40, 1);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Polygrafie - Inženýr', 30, 3);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Povrchová ochrana materiálů - Bakalář', 30, 3);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Speciální chemicko-biologické obory - Bakalář', 50, 2);

INSERT INTO SEM_STUD_PLAN (ID, NAZEV, ODHAD_STUDENTU, OBOR_ID)
VALUES (SEM_STUDIJNI_PLAN_SEQ.NEXTVAL, 'Speciální chemicko-biologické obory - Magistr', 50, 2);

-- endregion

-- region Předměty: --------------------------------------------------------------------------------------------------------

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IMSWS', 1, 1, 'Navrh a modelovani SW systemu');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IMAT1', 1, 1, 'Matematika 1');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IZALG', 1, 2, 'Zaklady algoritmizace');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IUDP', 1, 1, 'Architektura pocitacu');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IOPEX', 1, 2, 'Odborna praxe - exkurze I');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'ILALG', 1, 1, 'Linearni algebra');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IMAT1', 1, 1, 'Matematika 1');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IZIT', 1, 1, 'Zaklady informacnich technologii');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IZEK', 1, 1, 'Zaklady ekonomie');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IPALP', 2, 2, 'Praktikum z algoritmizace a programovani');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IMAT2', 2, 1, 'Matematika 2');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'ITEGR', 2, 1, 'Teorie grafu');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IZAPR', 2, 1, 'Zaklady programovani');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IZSE', 2, 1, 'Zaklady slaboproude elektrotechniky');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IIFZ', 1, 2, 'Informacni zdroje a jejich vyuzivani');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'ISPSY', 1, 2, 'Socialni psychologie');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IZIT', 1, 1, 'Zaklady informacnich technologii');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'ISPSY', 1, 2, 'Socialni psychologie');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IPRAV', 2, 2, 'Pravo');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'ITETP', 2, 1, 'Textove editory a tab. procesory');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IZKMA', 2, 1, 'Zaklady managementu');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IZMAR', 2, 1, 'Zaklady marketingu');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IMS1E', 1, 2, 'Matematicky seminar I');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IOOP', 1, 1, 'Objektove orientovane programovani');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IPS1', 1, 1, 'Pocitacove site I');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IPOGR', 1, 1, 'Pocitacova grafika');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'ISTAT', 1, 1, 'Statistika');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IUJC', 1, 1, 'Jazyk C');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IOOP', 1, 1, 'Objektove orientovane programovani');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IUJC', 1, 1, 'Jazyk C');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IOSYS', 2, 1, 'Operacni systemy');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IRPP2', 2, 2, 'Rizena prazdninova praxe II');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IMSW', 2, 1, 'Modelovani ve vypoctovych SW');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IC++1', 2, 1, 'Jazyk C++ I');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IDAS1', 2, 1, 'Databazove systemy I');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IDATS', 2, 1, 'Datove struktury');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IMTA', 2, 1, 'Mobilni technologie a aplikace');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IINMC', 1, 1, 'Uvod do novych medii a komunikace');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IZKMA', 1, 1, 'Zaklady managementu');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IZMAR', 1, 1, 'Zaklady marketingu');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IJAV', 2, 1, 'Programovaci techniky v jazyce Java');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IPS2', 2, 1, 'Pocitacove site II');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IPOG2', 2, 1, 'Pocitacova grafika II');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IGRED', 2, 1, 'Graficke editory');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IPSTP', 2, 2, 'Psychologie na trhu prace');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IDAS2', 1, 1, 'Databazove systemy II');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'ISOSY', 1, 1, 'Sprava operacnich systemu');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'ISEPR', 1, 2, 'Seminarni projekt');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IWWW', 1, 1, 'Navrh a tvorba WWW stranek');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IMOSI', 1, 1, 'Modelovani a simulace');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IEKPO', 1, 2, 'Ekonomika podniku');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IIRSP', 2, 1, 'Informacni a ridici systemy v praxi');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'ITEJA', 2, 1, 'Teorie jazyku');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'ICSHP', 2, 1, 'Programovani v .NET a C#');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IBIS', 2, 1, 'Bezpecnost informacnich systemu');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IOPE2', 2, 2, 'Odborna praxe - exkurze II');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'ISQBD', 2, 1, 'noSQL systemy a Big Data');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'ISPWE', 2, 1, 'Sprava webserveru');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IPS3', 1, 1, 'Pocitacove site III');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IGRED', 1, 1, 'Graficke editory');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'ICAD', 1, 1, 'Systemy CAD');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'I3DGR', 2, 1, '3D grafika');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IPNIN', 2, 1, 'Podnikani na Internetu');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IPS4', 2, 1, 'Pocitacove site IV');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'ISOS2', 2, 1, 'Sprava operacnich systemu II');

INSERT INTO SEM_PREDMET (ID, ZKRATKA, FORMA_VYUKY_ID, ZPUSOB_ZAKONCENI_ID, NAZEV)
VALUES (SEM_PREDMET_SEQ.NEXTVAL, 'IPDAE', 1, 1, 'Prenos dat a informaci');

-- endregion

-- region Místnosti: -----------------------------------------------------------------------------------------------
--Row 1
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL, '02013',15.0);
--Row 2
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'ZV',38.0);
--Row 3
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'02018',20.0);
--Row 4
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'SU104',15.0);
--Row 5
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'H1',224.0);
--Row 6
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'H2',116.0);
--Row 7
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'SEM403',30.0);
--Row 8
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'02017',40.0);
--Row 9
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'SEM402',80.0);
--Row 10
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'SEM404',60.0);
--Row 11
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'SU402',24.0);
--Row 12
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'SU301',30.0);
--Row 13
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'02057',50.0);
--Row 14
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'SU401',20.0);
--Row 15
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'02027',10.0);
--Row 16
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'EL203',15.0);
--Row 17
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'02031',20.0);
--Row 18
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'EL101',20.0);
--Row 19
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'EL102',20.0);
--Row 20
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'PC105',24.0);
--Row 21
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'02029',55.0);
--Row 22
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'02025',20.0);
--Row 23
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'02034',25.0);
--Row 24
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'02033',18.0);
--Row 25
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'02030',90.0);
--Row 26
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'02032',100.0);
--Row 27
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'EL204',10.0);
--Row 28
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'EL406',10.0);
--Row 29
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'EL407',16.0);
--Row 30
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'EL405',14.0);
--Row 31
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'EL408',8.0);
--Row 32
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'03012',80.0);
--Row 33
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'03053',60.0);
--Row 34
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'PC104',24.0);
--Row 35
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'NET101',8.0);
--Row 36
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'NET102',15.0);
--Row 37
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'03017',75.0);
--Row 38
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'03058',40.0);
--Row 39
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'03013',55.0);
--Row 40
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'03014',90.0);
--Row 41
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'03015',35.0);
--Row 42
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'03052',20.0);
--Row 43
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'03054',85.0);
--Row 44
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'PC406',20.0);
--Row 45
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'PC407',20.0);
--Row 46
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'IT401',20.0);
--Row 47
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'IT402',20.0);
--Row 48
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'03055',90.0);
--Row 49
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'03016',110.0);
--Row 50
INSERT INTO SEM_MISTNOST (ID, NAZEV, KAPACITA) VALUES (SEM_MISTNOST_SEQ.NEXTVAL,'03045',130.0);

-- endregion

-- region Uzivatele: --------------------------------------------------------------------------------------------------------

/**
 * Admin user (email: admin@admin.cz, password: admin).
 */
INSERT INTO sem_uzivatel (id, email, heslo, admin) VALUES (SEM_UZIVATEL_SEQ.NEXTVAL, 'admin@admin.cz', '$2y$10$5uWL4bwdr5f9RuZ.eNtJVO9kT5FYgJePD6XqmT7jRFNy50z2uVoXC', 1);

/**
 * Teacher-admin user (email: teacher@admin.cz, password: admin).
 */
INSERT INTO sem_uzivatel (id, email, heslo, admin, ucitel_id) VALUES (SEM_UZIVATEL_SEQ.NEXTVAL, 'teacher@admin.cz', '$2y$10$5uWL4bwdr5f9RuZ.eNtJVO9kT5FYgJePD6XqmT7jRFNy50z2uVoXC', 1, 1);

/**
 * Teacher user (email: teacher@teacher.cz, password: teacher).
 */
INSERT INTO sem_uzivatel (id, email, heslo, admin, ucitel_id) VALUES (SEM_UZIVATEL_SEQ.NEXTVAL, 'teacher@teacher.cz', '$2a$10$nAmwIgTiV3GuPwEo7EBXr.45jRBc5keNGZEAJsAVNzMVeRaT7zywK', 0, 2);

/**
 * No rights user (email: test@test.cz, password: test).
 */
INSERT INTO sem_uzivatel (id, email, heslo, admin) VALUES (SEM_UZIVATEL_SEQ.NEXTVAL, 'test@test.cz', '$2a$10$Gccc9Rausu3Yxzuhm8vNQueYEx8dE8SCjo/rRGKtBLC0KMkn9QgHq', 0);

-- endregion